### PR TITLE
Support for get and a few other things

### PR DESCRIPTION
**Pull request by jongilbraith**
I've added the ability to specify the http method in ttt_call() and in redirect and gather scopes.

_Important note:_ one of my changes is to modify the argument signature for ttt_call() to use an options hash.  Thought it would be tidier given the method would take the number of optional arguments to three.

Also did a few other minor little bits and bobs (tidying, etc).

### CODE REVIEW

**Comment by JMongol** [comment]
Thanks for the work on this! Looks great except for a small typo ("rasie" instead of "raise"). Ping me when you've fixed that and I'll merge, test, and republish the gem.

**Comment by jongilbraith** [comment]
Thanks Jack, commit pushed fixing typo.

Cheers!

Jon

**Comment by JMongol** [comment]
New gem is sitting on my computer ready to go, but rubygems.org is down (for push), so it will go up later today.

**Comment by jongilbraith** [comment]
Cheers Jack. Nearly home time here so will check back again in the morning.

**Pull request merged**
